// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCda_opZmgOkjzyunAusmc9Y5urr6nCiug',
    appId: '1:136781534517:web:c25d77a71fd9823c84a87c',
    messagingSenderId: '136781534517',
    projectId: 'learning--maps-58772',
    authDomain: 'learning--maps-58772.firebaseapp.com',
    storageBucket: 'learning--maps-58772.appspot.com',
    measurementId: 'G-MP8128D4N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuNErPEmvzjxb7xD3k3mIvADrDGlzkA58',
    appId: '1:136781534517:android:f327942ba57400a184a87c',
    messagingSenderId: '136781534517',
    projectId: 'learning--maps-58772',
    storageBucket: 'learning--maps-58772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQfpuQkWBCMF0eDP2R_l1a68NaEZ1zAIQ',
    appId: '1:136781534517:ios:9ecd83407673401c84a87c',
    messagingSenderId: '136781534517',
    projectId: 'learning--maps-58772',
    storageBucket: 'learning--maps-58772.appspot.com',
    iosClientId: '136781534517-78cgpg90qcsips7vf6c6f4qu09cmk29f.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQfpuQkWBCMF0eDP2R_l1a68NaEZ1zAIQ',
    appId: '1:136781534517:ios:9ecd83407673401c84a87c',
    messagingSenderId: '136781534517',
    projectId: 'learning--maps-58772',
    storageBucket: 'learning--maps-58772.appspot.com',
    iosClientId: '136781534517-78cgpg90qcsips7vf6c6f4qu09cmk29f.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMaps',
  );
}
